services:
  - type: web
    name: flex-gigs
    runtime: php
    plan: free
    buildCommand: ""
    startCommand: "heroku-php-apache2 public/"
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: SESSION_DRIVER
        value: cookie
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
